# Generated by Django 4.2 on 2023-04-13 18:25

from django.db import migrations, models

import requests


def populate_ability_scores(apps, schema_editor):
    base_url = "https://www.dnd5eapi.co"

    AbilityScore = apps.get_model("char_gen", "AbilityScore")

    response = requests.get(base_url + "/api/ability-scores")

    par_obj = response.json()

    for obj in par_obj.get('results'):
        score_response = requests.get(base_url + obj.get("url"))
        json_obj = score_response.json()

        model = AbilityScore(
            index=json_obj.get('index', 'n/a'),
            name=json_obj.get('name', 'N/A'),
            full_name=json_obj.get('full_name', 'N/A'),
            desc1=json_obj.get('desc', ['None', 'None'])[0],
            desc2=json_obj.get('desc', ['None', 'None'])[1],
            url=json_obj.get('url')
        )

        model.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=15)),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.RunPython(populate_ability_scores,
                             reverse_code=migrations.RunPython.noop)
    ]
