# Generated by Django 4.2 on 2023-04-13 19:01

from django.db import migrations, models
import django.db.models.deletion

import requests


def populate_skills(apps, schema_editor):
    base_url = "https://www.dnd5eapi.co"

    Skill = apps.get_model("char_gen", "Skill")
    AbilityScore = apps.get_model("char_gen", "AbilityScore")

    response = requests.get(base_url + "/api/skills")

    par_obj = response.json()

    for obj in par_obj.get('results'):
        score_response = requests.get(base_url + obj.get("url"))
        json_obj = score_response.json()

        model = Skill(
            index=json_obj.get('index', 'n/a'),
            name=json_obj.get('name', 'N/A'),
            desc=json_obj.get('desc', ['None'])[0],
            ability_score=AbilityScore.objects.get(
                index=json_obj.get('ability_score').get('index', None)),
            url=json_obj.get('url')
        )

        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('char_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('url', models.URLField()),
                ('ability_score', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='char_gen.abilityscore')),
            ],
        ),
        migrations.RunPython(populate_skills,
                             reverse_code=migrations.RunPython.noop)
    ]
