# Generated by Django 4.2 on 2023-04-13 19:21

from django.db import migrations, models

import requests


def populate_languages(apps, schema_editor):
    base_url = "https://www.dnd5eapi.co"

    Language = apps.get_model("char_gen", "Language")

    response = requests.get(base_url + "/api/languages")

    par_obj = response.json()

    for obj in par_obj.get('results'):
        score_response = requests.get(base_url + obj.get("url"))
        json_obj = score_response.json()

        model = Language(
            index=json_obj.get('index', 'n/a'),
            name=json_obj.get('name', 'N/A'),
            language_type=json_obj.get('type', 'None'),
            typical_speakers=json_obj.get('typical_speakers', []),
            script=json_obj.get('script', 'None'),
            url=json_obj.get('url')
        )

        model.save()


def populate_proficiencies(apps, schema_editor):
    base_url = "https://www.dnd5eapi.co"

    Proficiency = apps.get_model("char_gen", "Proficiency")

    response = requests.get(base_url + "/api/proficiencies")

    par_obj = response.json()

    for obj in par_obj.get('results'):
        score_response = requests.get(base_url + obj.get("url"))
        json_obj = score_response.json()

        model = Proficiency(
            index=json_obj.get('index', 'n/a'),
            name=json_obj.get('name', 'N/A'),
            proficiency_type=json_obj.get('type', 'None'),
            url=json_obj.get('url')
        )

        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('char_gen', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('language_type', models.CharField(max_length=20)),
                ('typical_speakers', models.JSONField()),
                ('script', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=30)),
                ('proficiency_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RunPython(populate_languages,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_proficiencies,
                             reverse_code=migrations.RunPython.noop)
    ]
