# Generated by Django 4.2 on 2023-04-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_gen', '0003_language_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScoreBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('ability_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_gen.abilityscore')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('choose', models.IntegerField()),
                ('choice_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageOptions',
            fields=[
                ('choiceoptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='char_gen.choiceoptions')),
                ('options', models.ManyToManyField(to='char_gen.language')),
            ],
            bases=('char_gen.choiceoptions',),
        ),
        migrations.CreateModel(
            name='ProficiencyOptions',
            fields=[
                ('choiceoptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='char_gen.choiceoptions')),
                ('options', models.ManyToManyField(to='char_gen.proficiency')),
            ],
            bases=('char_gen.choiceoptions',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('speed', models.IntegerField()),
                ('alignment', models.TextField()),
                ('age', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('size_desc', models.TextField()),
                ('language_desc', models.TextField()),
                ('url', models.URLField()),
                ('ability_bonuses', models.ManyToManyField(through='char_gen.AbilityScoreBonus', to='char_gen.abilityscore')),
                ('languages', models.ManyToManyField(to='char_gen.language')),
                ('starting_proficiencies', models.ManyToManyField(to='char_gen.proficiency')),
                ('language_options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='char_gen.languageoptions')),
                ('starting_proficiency_options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='char_gen.proficiencyoptions')),
            ],
        ),
        migrations.AddField(
            model_name='abilityscorebonus',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_gen.race'),
        ),
    ]
